name = "OperationsResearchApplications"
uuid = "1159fefd-670c-4920-82fb-fce65e238ad5"
authors = ["Ethan Buck"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1.4"
CSV = "0.7"
Cbc = "0.7"
DataFrames = "0.21"
JSON = "0.21"
JuMP = "0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
